config:
    batch: true
    title: Batch Add Lock Manager
    description: Batch addition of lock manager
    network: matic
    signer:
        type: 'Gnosis Safe'
        address: '0x30ceaeC1d8Ed347B91d45077721c309242db3D6d' # Foundation multisig
    contracts:
        publicLockGeneral: '0x4E0c80548e67A6E05464E540729222EB9812444d'
        publicLockRugPullDetector: '0x525d8d73f11a8586482F4f74C105D9d8B7cf73dA'
        publicLockScamDetector: '0x54089510Aec879CA42e08BC4B166be8362B56BB2'
        publicLockSpamDetector: '0x6453379CBC14f7a277319B6C8b7577Ae78524968'

proposals:
    - title: Add Lock Manager
      description: Add a lock manager
      contract: publicLockGeneral
      type: addLockManager
      args:
          address: '0x5854E0AbCec28EDead274FEF0ec6516087052E99'

    - title: Add Lock Manager
      description: Add a lock manager
      contract: publicLockRugPullDetector
      type: addLockManager
      args:
          address: '0x5854E0AbCec28EDead274FEF0ec6516087052E99'

    - title: Add Lock Manager
      description: Add a lock manager
      contract: publicLockScamDetector
      type: addLockManager
      args:
          address: '0x5854E0AbCec28EDead274FEF0ec6516087052E99'

    - title: Add Lock Manager
      description: Add a lock manager
      contract: publicLockSpamDetector
      type: addLockManager
      args:
          address: '0x5854E0AbCec28EDead274FEF0ec6516087052E99'
