name: Unit test subgraph
on: push
jobs:
  test-subgraph:
    name: Run Unit Test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Install subgraph dependencies
        working-directory: ./subgraph
        run: npm run install
      
      - name: Run test
        working-directory: ./subgraph
        run: npm run test