name: Prod Deploy Subgraph
on:
  workflow_dispatch:
    branches: [ master ]
jobs:
  deploy-subgraph:
    name: Deploy subgraph workflow
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Install the graph cli
        run: npm install @graphprotocol/graph-cli

      - name: Authenticate with prod subgraph
        run: |
          npx graph auth --product hosted-service ${{ secrets.PROD_SUBGRAPH_A_API_KEY }}

      - name: Install subgraph dependencies
        working-directory: ./subgraph
        run: npm install

      - name: Prepare for subgraph deployment
        working-directory: ./subgraph
        run: npm run prepare

      - name: Deploy subgraph 
        working-directory: ./subgraph
        run: npm run deploy
