name: Dev Deploy Subgraph
on: push
jobs:
  dev-deploy-subgraph:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Install the graph cli
        run: npm install -g @graphprotocol/graph-cli

      - name: Authenticate with dev subgraph
        run: graph auth --product hosted-service ${{ secrets.DEV_SUBGRAPH_API_KEY }}

      - name: Install subgraph dependencies
        working-directory: ./subgraph
        run: npm run install

      - name: Prepare for dev subgraph deployment
        working-directory: ./subgraph
        run: npm run prepare-dev

      - name: Deploy dev subgraph 
          working-directory: ./subgraph
          run: npm run deploy-dev